name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Replace with your main development branch

jobs:
  # build the project first and deploy it
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install
      # building our project
      - name: Build
        run: npm run build

      - name: Deploy to prod url
        # main is the branch name where new code is pushed
        if: github.ref == 'refs/heads/master'
        # this works for the deployment pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # when the above actions are made this will create a branch in the following page
          # when we uses build command this will create a dist folder and this branch will contain all the code specific to dist folder
          # this branch only contain the static file which exist in the dist folder

          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

# it might through permission error during deployment,
# go the repo settings, Action > General > Workflow permissions
# and select Read and Write permissions
# click save,
# re-run jobs and it should fix the error

# uses: peaceiris/actions-gh-pages@v3
# with:
#   github_token: ${{ secrets.GITHUB_TOKEN }}
#   publish_dir: ./dist
# publish_branch: prod-gh-pages  // by default it will create gh-pages branch and push everything of dist folder inside it.

# - name: Deploy to dev url
#   if: github.ref == 'refs/heads/develop'
#   uses: peaceiris/actions-gh-pages@v3
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
#     publish_dir: ./dist
#     # publish_branch: dev-gh-pages
